/**
 * Seeded demo parcels for the June 1 walkthrough.
 *
 * Hornbaker (GPIN 7596-81-5396) is the anchor demo case.
 * The other 9 are picked to show readiness-score differentiation across
 * the regulatory / environmental / power / political risk dimensions.
 *
 * Scores are hand-picked for the demo; production replaces with
 * pre-computed scores per Overlay_Specification.md.
 */
import type { SubScoreKey, DataQuality } from "@/store/useViraStore";

export interface DemoParcel {
  gpin: string;
  campusName: string;
  address: string;
  magisterialDistrict: string;
  acreage: number;
  zoning: string;
  insideDcoz: boolean;
  centroid: [number, number]; // [lng, lat]
  viraReadiness: number; // 0..100
  subScores: Record<SubScoreKey, number>;
  subScoreQuality: Record<SubScoreKey, DataQuality>;
  conviction: number; // 0..100
  status: "Hornbaker (live SUP)" | "Operating" | "Planned" | "Under Construction" | "Greenfield" | "Hard-blocked";
  notes: string;
  flags: {
    inRPA: boolean;
    inSFHA: boolean;
    federalLand: boolean;
    nearBattlefield: boolean;
    nearSubstation500kV: boolean;
    activeOpposition: boolean;
  };
}

export const DEMO_PARCELS: DemoParcel[] = [
  {
    gpin: "7596-81-5396",
    campusName: "Hornbaker Road (SUP2025-00016)",
    address: "Hornbaker Rd & Wellington Rd, Innovation Park",
    magisterialDistrict: "Brentsville",
    acreage: 40.02,
    zoning: "A-1 → M-2 (proposed)",
    insideDcoz: false,
    centroid: [-77.53347, 38.76185], // geometry-derived from Parcel.geojson (preprocess_score_parcels.py)
    viraReadiness: 71,
    subScores: {
      watershedVulnerability: 88,
      facilityWaterContext: 54,
      droughtExposure: 76,
      disclosureLegibility: 69,
      communityObsDensity: 48,
      municipalSupplyHeadroom: 80,
      stormwaterBurden: 42,
    },
    subScoreQuality: {
      watershedVulnerability: "M",
      facilityWaterContext: "M",
      droughtExposure: "M",
      disclosureLegibility: "Md",
      communityObsDensity: "Md",
      municipalSupplyHeadroom: "M",
      stormwaterBurden: "I",
    },
    conviction: 84,
    status: "Hornbaker (live SUP)",
    notes:
      "Outside DCOZ → requires SUP. 3 prior M-2 conversions in Brentsville averaged 14 mo; 1 denied. 4 community speakers in opposition (9/24/25 PC meeting). $534k LOS contributions proffered.",
    flags: {
      inRPA: false,
      inSFHA: false,
      federalLand: false,
      nearBattlefield: true,
      nearSubstation500kV: false,
      activeOpposition: true,
    },
  },
  {
    gpin: "7400-32-1100",
    campusName: "Compass Datacenters PWC Campus 1",
    address: "Pageland Ln, Gainesville",
    magisterialDistrict: "Gainesville",
    acreage: 884.07,
    zoning: "PBD",
    insideDcoz: false,
    centroid: [-77.6605, 38.8204],
    viraReadiness: 78,
    subScores: {
      watershedVulnerability: 92,
      facilityWaterContext: 72,
      droughtExposure: 70,
      disclosureLegibility: 71,
      communityObsDensity: 65,
      municipalSupplyHeadroom: 88,
      stormwaterBurden: 55,
    },
    subScoreQuality: {
      watershedVulnerability: "M",
      facilityWaterContext: "M",
      droughtExposure: "M",
      disclosureLegibility: "Md",
      communityObsDensity: "Md",
      municipalSupplyHeadroom: "M",
      stormwaterBurden: "I",
    },
    conviction: 92,
    status: "Planned",
    notes: "Approved REZ2022-00036. 11.5M sq ft planned GFA across 884 acres. Adjacent to existing transmission.",
    flags: {
      inRPA: false,
      inSFHA: false,
      federalLand: false,
      nearBattlefield: false,
      nearSubstation500kV: true,
      activeOpposition: false,
    },
  },
  {
    gpin: "7501-94-2027",
    campusName: "Digital Gateway North",
    address: "Pageland Ln, Gainesville",
    magisterialDistrict: "Gainesville",
    acreage: 534.0,
    zoning: "PMD",
    insideDcoz: true,
    centroid: [-77.6712, 38.8367],
    viraReadiness: 81,
    subScores: {
      watershedVulnerability: 95,
      facilityWaterContext: 86,
      droughtExposure: 68,
      disclosureLegibility: 71,
      communityObsDensity: 72,
      municipalSupplyHeadroom: 85,
      stormwaterBurden: 50,
    },
    subScoreQuality: {
      watershedVulnerability: "M",
      facilityWaterContext: "M",
      droughtExposure: "M",
      disclosureLegibility: "Md",
      communityObsDensity: "Md",
      municipalSupplyHeadroom: "M",
      stormwaterBurden: "I",
    },
    conviction: 90,
    status: "Planned",
    notes: "Inside DCOZ by-right. 7.0M sq ft GFA. Heavy community opposition due to battlefield proximity.",
    flags: {
      inRPA: false,
      inSFHA: false,
      federalLand: false,
      nearBattlefield: true,
      nearSubstation500kV: true,
      activeOpposition: true,
    },
  },
  {
    gpin: "7501-22-4015",
    campusName: "Digital Gateway South",
    address: "Pageland Ln, Gainesville",
    magisterialDistrict: "Gainesville",
    acreage: 342.0,
    zoning: "PMD",
    insideDcoz: true,
    centroid: [-77.6680, 38.8210],
    viraReadiness: 79,
    subScores: {
      watershedVulnerability: 92,
      facilityWaterContext: 85,
      droughtExposure: 66,
      disclosureLegibility: 71,
      communityObsDensity: 70,
      municipalSupplyHeadroom: 80,
      stormwaterBurden: 50,
    },
    subScoreQuality: {
      watershedVulnerability: "M",
      facilityWaterContext: "M",
      droughtExposure: "M",
      disclosureLegibility: "Md",
      communityObsDensity: "Md",
      municipalSupplyHeadroom: "M",
      stormwaterBurden: "I",
    },
    conviction: 89,
    status: "Planned",
    notes: "Inside DCOZ. 3.7M sq ft GFA. Same battlefield-adjacency politics as North.",
    flags: {
      inRPA: false,
      inSFHA: false,
      federalLand: false,
      nearBattlefield: true,
      nearSubstation500kV: true,
      activeOpposition: true,
    },
  },
  {
    gpin: "7595-44-0021",
    campusName: "Stack Infrastructure Manassas",
    address: "Wellington Rd, Manassas",
    magisterialDistrict: "Brentsville",
    acreage: 90.0,
    zoning: "M-2",
    insideDcoz: true,
    centroid: [-77.5081, 38.7610],
    viraReadiness: 87,
    subScores: {
      watershedVulnerability: 94,
      facilityWaterContext: 92,
      droughtExposure: 80,
      disclosureLegibility: 70,
      communityObsDensity: 82,
      municipalSupplyHeadroom: 86,
      stormwaterBurden: 70,
    },
    subScoreQuality: {
      watershedVulnerability: "M",
      facilityWaterContext: "M",
      droughtExposure: "M",
      disclosureLegibility: "Md",
      communityObsDensity: "Md",
      municipalSupplyHeadroom: "M",
      stormwaterBurden: "I",
    },
    conviction: 88,
    status: "Operating",
    notes: "Inside DCOZ by-right. M-2 zoning. Adjacent to Possum Point 230kV substation.",
    flags: {
      inRPA: false,
      inSFHA: false,
      federalLand: false,
      nearBattlefield: false,
      nearSubstation500kV: false,
      activeOpposition: false,
    },
  },
  {
    gpin: "7800-50-9921",
    campusName: "Prince William Forest Park (federal)",
    address: "Joplin Rd, Triangle",
    magisterialDistrict: "Coles",
    acreage: 15234.0,
    zoning: "FED",
    insideDcoz: false,
    centroid: [-77.4192, 38.5731],
    viraReadiness: 4,
    subScores: {
      watershedVulnerability: 22,
      facilityWaterContext: 0,
      droughtExposure: 0,
      disclosureLegibility: 60,
      communityObsDensity: 0,
      municipalSupplyHeadroom: 0,
      stormwaterBurden: 0,
    },
    subScoreQuality: {
      watershedVulnerability: "M",
      facilityWaterContext: "M",
      droughtExposure: "M",
      disclosureLegibility: "Md",
      communityObsDensity: "Md",
      municipalSupplyHeadroom: "M",
      stormwaterBurden: "I",
    },
    conviction: 95,
    status: "Hard-blocked",
    notes: "Federal land — National Park Service. Categorically off the private development market. Shown for contrast.",
    flags: {
      inRPA: true,
      inSFHA: false,
      federalLand: true,
      nearBattlefield: false,
      nearSubstation500kV: false,
      activeOpposition: false,
    },
  },
  {
    gpin: "8290-12-3304",
    campusName: "Occoquan SFHA parcel",
    address: "Occoquan River bank, Woodbridge",
    magisterialDistrict: "Occoquan",
    acreage: 22.5,
    zoning: "B-1",
    insideDcoz: false,
    centroid: [-77.2592, 38.6840],
    viraReadiness: 18,
    subScores: {
      watershedVulnerability: 65,
      facilityWaterContext: 35,
      droughtExposure: 5,
      disclosureLegibility: 55,
      communityObsDensity: 40,
      municipalSupplyHeadroom: 18,
      stormwaterBurden: 45,
    },
    subScoreQuality: {
      watershedVulnerability: "M",
      facilityWaterContext: "M",
      droughtExposure: "M",
      disclosureLegibility: "Md",
      communityObsDensity: "Md",
      municipalSupplyHeadroom: "M",
      stormwaterBurden: "I",
    },
    conviction: 73,
    status: "Greenfield",
    notes: "Inside FEMA Zone AE (1% annual flood) + RPA buffer. Practically undevelopable. Shown for contrast.",
    flags: {
      inRPA: true,
      inSFHA: true,
      federalLand: false,
      nearBattlefield: false,
      nearSubstation500kV: false,
      activeOpposition: false,
    },
  },
  {
    gpin: "7596-11-8842",
    campusName: "Innovation Park I-4 (greenfield)",
    address: "University Blvd, Innovation Park",
    magisterialDistrict: "Brentsville",
    acreage: 67.0,
    zoning: "M/T",
    insideDcoz: true,
    centroid: [-77.5435, 38.7565],
    viraReadiness: 84,
    subScores: {
      watershedVulnerability: 90,
      facilityWaterContext: 88,
      droughtExposure: 82,
      disclosureLegibility: 71,
      communityObsDensity: 80,
      municipalSupplyHeadroom: 88,
      stormwaterBurden: 72,
    },
    subScoreQuality: {
      watershedVulnerability: "M",
      facilityWaterContext: "M",
      droughtExposure: "M",
      disclosureLegibility: "Md",
      communityObsDensity: "Md",
      municipalSupplyHeadroom: "M",
      stormwaterBurden: "I",
    },
    conviction: 80,
    status: "Greenfield",
    notes: "Undeveloped LRLU I-4. Inside DCOZ, M/T zoning, adjacent to GMU Innovation campus. Strongest greenfield opportunity in dataset.",
    flags: {
      inRPA: false,
      inSFHA: false,
      federalLand: false,
      nearBattlefield: false,
      nearSubstation500kV: false,
      activeOpposition: false,
    },
  },
  {
    gpin: "7704-88-4412",
    campusName: "Manassas Battlefield buffer parcel",
    address: "Pageland Ln, near Manassas Battlefield",
    magisterialDistrict: "Gainesville",
    acreage: 95.0,
    zoning: "A-1",
    insideDcoz: false,
    centroid: [-77.6920, 38.8425],
    viraReadiness: 31,
    subScores: {
      watershedVulnerability: 78,
      facilityWaterContext: 25,
      droughtExposure: 55,
      disclosureLegibility: 70,
      communityObsDensity: 22,
      municipalSupplyHeadroom: 62,
      stormwaterBurden: 8,
    },
    subScoreQuality: {
      watershedVulnerability: "M",
      facilityWaterContext: "M",
      droughtExposure: "M",
      disclosureLegibility: "Md",
      communityObsDensity: "Md",
      municipalSupplyHeadroom: "M",
      stormwaterBurden: "I",
    },
    conviction: 78,
    status: "Greenfield",
    notes: "A-1 agricultural, outside DCOZ. Directly faces Manassas Battlefield. § 32-509.02(4)(G) building color restrictions apply. Heavy opposition risk.",
    flags: {
      inRPA: false,
      inSFHA: false,
      federalLand: false,
      nearBattlefield: true,
      nearSubstation500kV: true,
      activeOpposition: true,
    },
  },
  {
    gpin: "7596-77-2310",
    campusName: "QTS Manassas Phase 2",
    address: "Innovation Park, Manassas",
    magisterialDistrict: "Brentsville",
    acreage: 50.0,
    zoning: "PBD",
    insideDcoz: true,
    centroid: [-77.5298, 38.7748],
    viraReadiness: 83,
    subScores: {
      watershedVulnerability: 92,
      facilityWaterContext: 90,
      droughtExposure: 78,
      disclosureLegibility: 70,
      communityObsDensity: 78,
      municipalSupplyHeadroom: 84,
      stormwaterBurden: 68,
    },
    subScoreQuality: {
      watershedVulnerability: "M",
      facilityWaterContext: "M",
      droughtExposure: "M",
      disclosureLegibility: "Md",
      communityObsDensity: "Md",
      municipalSupplyHeadroom: "M",
      stormwaterBurden: "I",
    },
    conviction: 86,
    status: "Under Construction",
    notes: "Inside DCOZ. QTS hyperscale campus expansion. Solid execution case study.",
    flags: {
      inRPA: false,
      inSFHA: false,
      federalLand: false,
      nearBattlefield: false,
      nearSubstation500kV: false,
      activeOpposition: false,
    },
  },
];

export function getParcelByGpin(gpin: string | null): DemoParcel | undefined {
  if (!gpin) return undefined;
  return DEMO_PARCELS.find((p) => p.gpin === gpin);
}
