"use client";

/**
 * Loads the pre-computed Water Legibility scores for every PWC parcel.
 * The JSON is generated by /preprocess_score_parcels.py and served as a
 * static asset from /public/data/parcels_scored.json.gz.
 *
 * Each record is a per-parcel scored attribute bag (no geometry).
 * Geometry lives in the PMTiles vector tile, joined visually by GPIN.
 *
 * On load we ALSO pre-synthesize the 7 sub-scores for every parcel (one-time
 * pass over ~159k records). Both the Terminal table and the right panel
 * derive their headline Water Legibility number from these synthesized
 * sub-scores (weighted by user-tunable subScoreWeights), so the two views
 * always agree.
 */
import { useEffect, useState } from "react";
import { synthesizeSubScores, type SubScoreRecord, type SubScoreQualityRecord } from "@/lib/synthesizeSubScores";

export interface ScoredParcel {
  GPIN: string;
  Acreage: number | null;
  acres: number;
  StreetNumber: string | null;
  StreetName: string | null;
  StreetType: string | null;
  City: string | null;
  ZipCode: string | null;
  SubdivisionName: string | null;
  zoning: string | null;
  lrlu: string | null;
  has_proffers?: 0 | 1;  // this zoning district has a proffered rezoning on record (may attach water/stormwater conditions)
  // Parcel centroid in WGS84 (lng, lat) — for map fly-to
  cx?: number;
  cy?: number;

  // ── Data center context (kept from Vira — same source files) ───────────
  in_dc_campus?: 0 | 1;
  in_dc_building?: 0 | 1;
  dc_campus_name?: string | null;
  dc_campus_status?: string | null;
  dc_building_name?: string | null;
  n_dc_buildings?: number;

  // ── Watershed ────────────────────────────────────────────────────────
  watershed_id?: string | null;
  watershed_name?: string | null;
  watershed_acres?: number | null;
  watershed_major_basin?: string | null;
  watershed_mgmt_plan_number?: string | null;  // PWC Watershed Management Plan section reference — a citable lead, not fetched document content
  n_dc_in_watershed?: number;
  n_dc_in_major_basin?: number;

  // ── Hydrology proximity ─────────────────────────────────────────────
  d_stream_ft?: number | null;
  d_hydro_ft?: number | null;
  d_spring_ft?: number | null;
  d_surftemp_ft?: number | null;
  nearest_surftemp_val?: number | null;
  rpa?: 0 | 1;
  wetland?: 0 | 1;
  in_tidal_flow_path?: 0 | 1;
  near_protected_open_space?: 0 | 1;
  near_h2oquality_protected_land?: 0 | 1;
  stream_order?: number | null;      // Stream.StreamType at nearest segment (2-6 observed)
  stream_name?: string | null;
  tidal_class?: string | null;       // VA WQS CLASS of nearest tidal segment, if within trigger range
  tidal_zone?: string | null;

  // ── Surface water temperature trend (VA DEQ Mann-Kendall/Theil-Sen) ──
  surftemp_trend?: string | null;       // "DEGRADING" | "NO TREND" | "IMPROVING"
  surftemp_tau?: number | null;         // Kendall's Tau (trend strength)
  surftemp_theilsen_slope?: number | null; // deg F per year
  surftemp_pvalcovs?: number | null;    // significance
  surftemp_stream?: string | null;

  // ── Nearest historical spring/groundwater chemistry (VA DEQ, statewide) ──
  spring_ph?: number | null;
  spring_spcond?: number | null;
  spring_no3no2?: number | null;
  spring_hardness?: number | null;
  spring_sample_date?: string | null;

  // ── Drought / climate (countywide constants, same on every parcel) ──
  pdsi?: number | null;
  phdi?: number | null;
  pmdi?: number | null;
  palmer_z?: number | null;
  avg_temp_f?: number | null;
  max_temp_f?: number | null;
  min_temp_f?: number | null;
  cdd?: number | null;
  hdd?: number | null;
  precip_in?: number | null;
  precip_normal_in?: number | null;
  precip_manassas_in?: number | null;
  snowfall_manassas_in?: number | null;
  precip_vienna_in?: number | null;
  snowfall_vienna_in?: number | null;
  min_temp_vienna_f?: number | null;

  // ── Disclosure / NPDES ───────────────────────────────────────────────
  has_npdes?: 0 | 1;
  has_deq_permit?: 0 | 1;
  npdes_facility_name?: string | null;
  n_npdes_violations?: number;
  dmr_flow_mgd?: number | null;
  dmr_nodi_code?: string | null;
  general_permit_type?: string | null;
  compliance_status?: string | null;
  last_inspection_date?: string | null;
  ej_score?: number | null;
  frs_id?: string | null;

  // ── Community monitoring ────────────────────────────────────────────
  n_wqp_stations_1mi?: number;
  n_deq_monitoring_1mi?: number;
  n_deq_gage_1mi?: number;           // DEQ stations with STA_LV4_CODE='GAGE' — actual flow-measurement points
  nearest_benthic_n?: number | null; // benthic-macroinvertebrate sample count at nearest DEQ station
  n_inat_1mi?: number;
  n_inat_research_1mi?: number;      // iNaturalist observations filtered to quality_grade='research'

  // ── Municipal supply (countywide constants) ─────────────────────────
  pw_water_pct_avg?: number | null;
  pw_water_pct_peak?: number | null;
  utility_aggregate_available?: 0 | 1;
  n_queued_projects_nearby?: number;
  pjm_zone_load_growth_pct?: number | null;

  // ── Stormwater / dam / soil (kept from Vira preprocessing) ──────────
  sw_segments?: number;
  sw_facilities?: number;
  sw_structures?: number;
  dam?: 0 | 1;
  dam_haz_class?: string | null;
  soil_cat?: string | null;
  hsg?: string | null;                    // Hydrologic Soil Group A (high infiltration) .. D (high runoff)
  erosion_susceptibility?: number | null;
  soil_permeability?: number | null;
  land_cover?: string | null;
  // Gage HEIGHT (ft), not discharge — no rating curve to convert to cfs is
  // available in this corpus, so no 7Q10 low-flow statistic is computed
  // from it (see preprocess_score_parcels.py for the full rationale and the
  // source-directory mislabeling this corrects).
  cedar_run_gage_height_ft?: number | null;
  gw_depth_ft?: number | null;

  // ── Land use / permitting context ───────────────────────────────────
  n_use_permits_on_parcel?: number;
  n_bza_1mi?: number;
  n_pending_nearby?: number;
  in_lrlu_developable?: 0 | 1;
  is_state_land?: 0 | 1;
  d_transmission_ft?: number | null;
  d_hv_transmission_ft?: number | null;   // nearest IN-SERVICE >=230kV HIFLD line only
  nearest_hv_sub_1?: string | null;
  nearest_hv_sub_2?: string | null;

  readiness: number;   // Python sort-bootstrap hint, 0..100 (not displayed directly)
  conviction: number;  // Python sort-bootstrap hint, 0..100 (not displayed directly)
}

let _cache: ScoredParcel[] | null = null;
// GPIN → synthesized 7 sub-scores. Populated once when parcels load; reused
// by the table + panel hot paths.
const _synthCache: Map<string, { subScores: SubScoreRecord; quality: SubScoreQualityRecord }> = new Map();

/** Lookup the cached synthesized sub-scores for a GPIN. */
export function getCachedSynth(gpin: string) {
  return _synthCache.get(gpin);
}

/** Read-only access to the synth cache (for batch operations like sorting). */
export function getSynthCache() {
  return _synthCache;
}

export function useScoredParcels() {
  const [parcels, setParcels] = useState<ScoredParcel[] | null>(_cache);
  const [loading, setLoading] = useState(_cache === null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (_cache !== null) {
      setParcels(_cache);
      setLoading(false);
      return;
    }
    let cancelled = false;
    setLoading(true);
    // We ship the parcel scores as a pre-gzipped artifact and decompress in
    // the browser via DecompressionStream (streaming, ~50ms on modern
    // hardware, supported in every evergreen browser since 2023).
    fetch("/data/parcels_scored.json.gz")
      .then((r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status} — score file not ready yet?`);
        if (!r.body) throw new Error("missing response body");
        const stream = r.body.pipeThrough(new DecompressionStream("gzip"));
        return new Response(stream).json();
      })
      .then((data: ScoredParcel[]) => {
        if (cancelled) return;
        _cache = data;
        // One-time synthesize pass — every row gets its 7 sub-scores cached so
        // both the table and the panel can read them in O(1) at render time.
        const t0 = performance.now();
        for (const p of data) {
          if (!p.GPIN) continue;
          _synthCache.set(p.GPIN, synthesizeSubScores(p));
        }
        // eslint-disable-next-line no-console
        console.log(`[Water Atlas] Synthesized ${_synthCache.size.toLocaleString()} parcels in ${Math.round(performance.now() - t0)}ms`);
        setParcels(data);
        setLoading(false);
      })
      .catch((e) => {
        if (cancelled) return;
        setError(String(e));
        setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, []);

  return { parcels, loading, error };
}

/** Build a display address from the parcel fields. */
export function parcelAddress(p: ScoredParcel): string {
  const parts = [p.StreetNumber, p.StreetName, p.StreetType].filter(Boolean).join(" ").trim();
  const city = [p.City, p.ZipCode].filter(Boolean).join(" ");
  return [parts, city].filter(Boolean).join(", ");
}

/** Single-parcel lookup using the in-memory cache (fast). */
export function findScoredParcel(gpin: string): ScoredParcel | undefined {
  if (!_cache) return undefined;
  return _cache.find((p) => p.GPIN === gpin);
}
